/*
 * Swagger Petstore
 *
 * A sample API that uses a petstore as an example to demonstrate features in the OpenAPI 3.0 specification
 *
 * API version: 1.0.0
 * Contact: apiteam@swagger.io
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package model

type Pet struct {

	// Name of the pet
	Name string `json:"name"`

	// Type of the pet
	Tag string `json:"tag,omitempty"`

	// Unique id of the pet
	Id int64 `json:"id"`
}
