openapi: 3.0.3
info:
  title: SeefsAPI文档 template
  description: 自用API文档模板
  version: 1.0.0
servers:
  - url: 'https://localhost:8080/'
paths:
  /ping:
    get:
      description: 测试服务器是否连通
      responses:
        200:
          description: 成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pet'
      requestBody:
        description: ping消息
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Pet'
components:
  schemas:
    Pet:
      allOf:
        - required:
            - id
          properties:
            id:
              type: integer
              format: int64
              description: Unique id of the pet